
version: 2

sources:
    - name: staging
      database: d2b_accessment
      schema: samumghe3893_staging
      tables:
          - name: orders
            description: "Product orders table"
          - name: reviews
            description: "Customer reviews table"
          - name: shipment_deliveries
            description: "Shipments deliveries table"
    - name: if_common
      database: d2b_accessment
      schema: if_common
      tables:
          - name: dim_addresses
            description: "Addresses dimension table"
          - name: dim_customers
            description: "Customers dimension table"
          - name: dim_dates
            description: "Dates dimension table"
          - name: dim_products
            description: "Products dimension table"
# models:
#   - meta:
#       fal:
#         scripts:
#           before:
#             - fal_scripts/load_data.py