
version: 2

sources:
    - name: staging
      database: d2b_accessment
      schema: samumghe3893_staging
      tables:
          - name: orders
            description: "Product orders table"
          - name: reviews
            description: "Customer reviews table"
          - name: shipment_deliveries
            description: "Shipments deliveries table"
# models:
#   - meta:
#       fal:
#         scripts:
#           before:
#             - fal_scripts/load_data.py